---
apiVersion: v1
kind: Service
metadata:
  name: ubiquity
  labels:
    app: ubiquity
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
  type: LoadBalancer
  selector:
    app: ubiquity
---
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: ubiquity
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubiquity
    spec:
      containers:
      - name: ubiquity
        image: IBMubiquityIMAGE # place holder
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
          name: ubiquity-port
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
           claimName: ubiquity-pvc